In [58]:
# ============================================================
#  KcELECTRA 광고 분류 파인튜닝
#  기반 모델 : beomi/KcELECTRA-base
#  분류 목표 : review_body → is_ad (0: 비광고, 1: 광고)
#  탐색 방식 : Grid Search (54 조합)
#  평가 기준 : Recall 1순위, F1-score 2순위
# ============================================================

# ── 0. 패키지 설치 (Colab 최초 1회) ──────────────────────────
!pip install transformers datasets scikit-learn pandas torch -q

In [59]:
# ── 1. 임포트 ─────────────────────────────────────────────────
import re
import os
import random
import itertools
import warnings
from html import unescape

import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from torch.nn import CrossEntropyLoss

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback,
)
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    recall_score, f1_score, precision_score, accuracy_score,
    classification_report,
)
from sklearn.utils.class_weight import compute_class_weight

warnings.filterwarnings("ignore")

In [60]:
# ── 2. 시드 고정 ───────────────────────────────────────────────
SEED = 42

def set_seed(seed: int = SEED):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)

set_seed()

In [61]:
# ── 3. 전처리 함수 ─────────────────────────────────────────────
def preprocess(text: str) -> str:
    """
    review_body 전처리
    1) HTML 엔티티 디코딩  (&amp; → &)
    2) HTML 태그 제거      (<b>텍스트</b> → 텍스트)
    3) 해시태그 단어 추출  (#맛집 → 맛집)  ← 광고 피처 보존
    4) 말줄임 제거         (... → 공백)
    5) 특수문자 정리       (한글/영문/숫자/기본문장부호만 유지)
    6) 과도한 공백 정리
    """
    if not isinstance(text, str):
        return ""
    text = unescape(text)
    text = re.sub(r"<[^>]+>", "", text)
    text = re.sub(r"#(\w+)", r"\1 ", text)
    text = re.sub(r"\.{2,}", " ", text)
    text = re.sub(r"[^\w\s가-힣ㄱ-ㅎㅏ-ㅣa-zA-Z0-9.,!?~]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

In [62]:
# ── 4. CSV 로드 및 전처리 ──────────────────────────────────────
TRAIN_CSV_PATH = "/content/CrawlingReviewList_rows.csv"   # ← 학습용
TEST_CSV_PATH  = "/content/APIReviewList_rows.csv"             # ← 평가용

print("=" * 60)
print("[1] 데이터 로드 및 전처리")
print("=" * 60)

============================================================
[1] 데이터 로드 및 전처리
============================================================

In [63]:
# ── Train 데이터 (크롤링) ──────────────────────────────────────
train_raw = pd.read_csv(TRAIN_CSV_PATH)
print(f"  [Train] 원본 행 수 : {len(train_raw)}")

train_raw = train_raw[["review_body", "is_ad"]].copy()
train_raw.rename(columns={"review_body": "review_description"}, inplace=True)  # 컬럼명 통일
train_raw.dropna(subset=["review_description", "is_ad"], inplace=True)
train_raw["is_ad"] = train_raw["is_ad"].astype(int)
train_raw["review_description"] = train_raw["review_description"].apply(preprocess)
train_df = train_raw[train_raw["review_description"].str.len() > 0].reset_index(drop=True)

print(f"  [Train] 전처리 후 행 수 : {len(train_df)}")
print(f"  [Train] 레이블 분포")
for label, count in train_df["is_ad"].value_counts().sort_index().items():
    print(f"    {label} ({'광고' if label==1 else '비광고'}) : {count}건 ({count/len(train_df)*100:.1f}%)")

# ── Test 데이터 (API) ──────────────────────────────────────────
test_raw = pd.read_csv(TEST_CSV_PATH)
print(f"\n  [Test]  원본 행 수 : {len(test_raw)}")

test_raw = test_raw[["review_description", "is_ad"]].copy()
test_raw.dropna(subset=["review_description", "is_ad"], inplace=True)
test_raw["is_ad"] = test_raw["is_ad"].astype(int)
test_raw["review_description"] = test_raw["review_description"].apply(preprocess)
test_df = test_raw[test_raw["review_description"].str.len() > 0].reset_index(drop=True)

print(f"  [Test]  전처리 후 행 수 : {len(test_df)}")
print(f"  [Test]  레이블 분포")
for label, count in test_df["is_ad"].value_counts().sort_index().items():
    print(f"    {label} ({'광고' if label==1 else '비광고'}) : {count}건 ({count/len(test_df)*100:.1f}%)")

print(f"\n  Train : {len(train_df)}건  |  Test : {len(test_df)}건")

  [Train] 원본 행 수 : 1051
  [Train] 전처리 후 행 수 : 1050
  [Train] 레이블 분포
    0 (비광고) : 729건 (69.4%)
    1 (광고) : 321건 (30.6%)

  [Test]  원본 행 수 : 1673
  [Test]  전처리 후 행 수 : 1307
  [Test]  레이블 분포
    0 (비광고) : 790건 (60.4%)
    1 (광고) : 517건 (39.6%)

  Train : 1050건  |  Test : 1307건

In [64]:
# ── 5. 클래스 가중치 계산 (Train 기준) ───────────────────────
print("\n" + "=" * 60)
print("[2] 클래스 가중치 계산")
print("=" * 60)

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.array([0, 1]),
    y=train_df["is_ad"].values,
)
class_weights_tensor = torch.tensor(class_weights, dtype=torch.float)
print(f"  클래스 가중치 → 비광고(0): {class_weights[0]:.4f} / 광고(1): {class_weights[1]:.4f}")

============================================================
[2] 클래스 가중치 계산
============================================================
  클래스 가중치 → 비광고(0): 0.7202 / 광고(1): 1.6355

In [65]:
# ── 7. Dataset 클래스 ──────────────────────────────────────────
MODEL_NAME = "beomi/KcELECTRA-base"
MAX_LEN    = 512   # KcELECTRA max_position_embeddings 기준

class AdDataset(Dataset):
    def __init__(self, texts, labels, tokenizer):
        self.encodings = tokenizer(
            list(texts),
            truncation=True,
            padding="max_length",
            max_length=MAX_LEN,
            return_tensors="pt",
        )
        self.labels = torch.tensor(list(labels), dtype=torch.long)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {
            "input_ids":      self.encodings["input_ids"][idx],
            "attention_mask": self.encodings["attention_mask"][idx],
            "token_type_ids": self.encodings.get(
                "token_type_ids",
                torch.zeros_like(self.encodings["input_ids"])
            )[idx],
            "labels": self.labels[idx],
        }

In [66]:
# ── 8. 평가 함수 ───────────────────────────────────────────────
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {
        "recall":    recall_score(labels, preds, pos_label=1, zero_division=0),
        "f1":        f1_score(labels, preds, pos_label=1, zero_division=0),
        "precision": precision_score(labels, preds, pos_label=1, zero_division=0),
        "accuracy":  accuracy_score(labels, preds),
    }

In [67]:
# ── 9. 클래스 가중치 적용 커스텀 Trainer ──────────────────────
class WeightedTrainer(Trainer):
    def __init__(self, class_weights, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.class_weights = class_weights.to(self.args.device)

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits
        loss_fn = CrossEntropyLoss(weight=self.class_weights)
        loss = loss_fn(logits, labels)
        return (loss, outputs) if return_outputs else loss

In [68]:
# ── 10. 하이퍼파라미터 그리드 ─────────────────────────────────
LEARNING_RATES = [1e-5, 3e-5, 5e-5]
SCHEDULERS     = ["linear", "cosine", "cosine_with_restarts"]
DROPOUTS       = [0.1, 0.2, 0.3]
BATCH_SIZES    = [16, 32]
EPOCHS         = 5

grid = list(itertools.product(LEARNING_RATES, SCHEDULERS, DROPOUTS, BATCH_SIZES))

print("\n" + "=" * 60)
print("[3] Grid Search 시작")
print(f"    총 실험 조합 : {len(grid)}가지")
print(f"    최대 Epoch   : {EPOCHS}")
print("=" * 60)

============================================================
[3] Grid Search 시작
    총 실험 조합 : 54가지
    최대 Epoch   : 5
============================================================

In [69]:
# ── 11. 토크나이저 로드 (1회만) ────────────────────────────────
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

# Test Dataset은 고정 (매 실험 동일)
test_dataset = AdDataset(test_df["review_description"], test_df["is_ad"], tokenizer)

In [70]:
# ── 12. Grid Search 루프 ───────────────────────────────────────
results = []
RESULTS_PATH = "electra2crawling_results_all.csv"

for exp_idx, (lr, scheduler, dropout, batch_size) in enumerate(grid, start=1):

    print(f"\n[실험 {exp_idx:02d}/{len(grid)}]  "
          f"lr={lr}  scheduler={scheduler}  "
          f"dropout={dropout}  batch={batch_size}")

    set_seed()  # 매 실험마다 시드 재고정

    # Train Dataset 구성
    train_dataset = AdDataset(
        train_df["review_description"], train_df["is_ad"], tokenizer
    )

    # 모델 초기화 (dropout 적용)
    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=2,
        hidden_dropout_prob=dropout,
        attention_probs_dropout_prob=dropout,
        ignore_mismatched_sizes=True,
    )

    # TrainingArguments
    training_args = TrainingArguments(
        output_dir=f"./ckpt/exp_{exp_idx:02d}",
        num_train_epochs=EPOCHS,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=64,
        learning_rate=lr,
        lr_scheduler_type=scheduler,
        warmup_ratio=0.1,
        weight_decay=0.01,
        eval_strategy="epoch",
        logging_strategy="epoch",
        save_strategy="no",
        load_best_model_at_end=False,
        metric_for_best_model="recall",   # Recall 기준으로 best 선택
        greater_is_better=True,
        logging_steps=50,
        seed=SEED,
        fp16=torch.cuda.is_available(),   # GPU 있으면 FP16 사용
        report_to="none",                 # wandb 등 비활성화
    )

    # WeightedTrainer
    trainer = WeightedTrainer(
        class_weights=class_weights_tensor,
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=test_dataset,
        compute_metrics=compute_metrics,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
    )

    # 학습
    trainer.train()

       # ── log_history에서 epoch별 지표 추출 ─────────────────────
    log_history    = trainer.state.log_history
    train_logs     = [x for x in log_history if "loss" in x and "eval_loss" not in x]
    eval_loss_logs = [x for x in log_history if "eval_loss" in x]
    eval_logs      = [x for x in log_history if "eval_recall" in x]

    # 전체 best 결과 (recall 최고 epoch 기준)
    best_eval = max(eval_logs, key=lambda x: x["eval_recall"])
    recall    = best_eval.get("eval_recall",    0)
    f1        = best_eval.get("eval_f1",        0)
    precision = best_eval.get("eval_precision", 0)
    accuracy  = best_eval.get("eval_accuracy",  0)

    print(f"  → Recall={recall:.4f}  F1={f1:.4f}  "
          f"Precision={precision:.4f}  Accuracy={accuracy:.4f}")

    # ── row 구성 (전체 best + epoch별 상세) ───────────────────
    row = {
        "exp_id":        exp_idx,
        "learning_rate": lr,
        "scheduler":     scheduler,
        "dropout":       dropout,
        "batch_size":    batch_size,
        "recall":        round(recall,    4),
        "f1":            round(f1,        4),
        "precision":     round(precision, 4),
        "accuracy":      round(accuracy,  4),
    }

    # epoch별 상세 지표 추가
    for i in range(EPOCHS):
        ep = i + 1

        row[f"epoch{ep}_train_loss"] = (
            round(train_logs[i].get("loss", 0), 4)
            if i < len(train_logs) else None
        )
        row[f"epoch{ep}_val_loss"] = (
            round(eval_loss_logs[i].get("eval_loss", 0), 4)
            if i < len(eval_loss_logs) else None
        )
        row[f"epoch{ep}_batch_size"] = (
            batch_size if i < len(eval_loss_logs) else None
        )
        row[f"epoch{ep}_recall"] = (
            round(eval_logs[i].get("eval_recall", 0), 4)
            if i < len(eval_logs) else None
        )
        row[f"epoch{ep}_f1"] = (
            round(eval_logs[i].get("eval_f1", 0), 4)
            if i < len(eval_logs) else None
        )
        row[f"epoch{ep}_precision"] = (
            round(eval_logs[i].get("eval_precision", 0), 4)
            if i < len(eval_logs) else None
        )
        row[f"epoch{ep}_accuracy"] = (
            round(eval_logs[i].get("eval_accuracy", 0), 4)
            if i < len(eval_logs) else None
        )

    # 결과 저장
    results.append(row)

    # 실험마다 즉시 CSV 저장 (런타임 끊겨도 복구 가능)
    pd.DataFrame(results).to_csv(RESULTS_PATH, index=False, encoding="utf-8-sig")

    # 메모리 정리
    del model, trainer, train_dataset
    torch.cuda.empty_cache()

[실험 01/54]  lr=1e-05  scheduler=linear  dropout=0.1  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.1141  F1=0.1973  Precision=0.7284  Accuracy=0.6327

[실험 02/54]  lr=1e-05  scheduler=linear  dropout=0.1  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.1779  F1=0.2784  Precision=0.6389  Accuracy=0.6350

[실험 03/54]  lr=1e-05  scheduler=linear  dropout=0.2  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.2824  F1=0.3935  Precision=0.6489  Accuracy=0.6557

[실험 04/54]  lr=1e-05  scheduler=linear  dropout=0.2  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.1064  F1=0.1858  Precision=0.7333  Accuracy=0.6312

[실험 05/54]  lr=1e-05  scheduler=linear  dropout=0.3  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.0000  F1=0.0000  Precision=0.0000  Accuracy=0.6044

[실험 06/54]  lr=1e-05  scheduler=linear  dropout=0.3  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.0000  F1=0.0000  Precision=0.0000  Accuracy=0.6044

[실험 07/54]  lr=1e-05  scheduler=cosine  dropout=0.1  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.3482  F1=0.4500  Precision=0.6360  Accuracy=0.6634

[실험 08/54]  lr=1e-05  scheduler=cosine  dropout=0.1  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.1373  F1=0.2287  Precision=0.6827  Accuracy=0.6335

[실험 09/54]  lr=1e-05  scheduler=cosine  dropout=0.2  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.5725  F1=0.5827  Precision=0.5932  Accuracy=0.6756

[실험 10/54]  lr=1e-05  scheduler=cosine  dropout=0.2  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.1122  F1=0.1933  Precision=0.6988  Accuracy=0.6297

[실험 11/54]  lr=1e-05  scheduler=cosine  dropout=0.3  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.0000  F1=0.0000  Precision=0.0000  Accuracy=0.6044

[실험 12/54]  lr=1e-05  scheduler=cosine  dropout=0.3  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.0000  F1=0.0000  Precision=0.0000  Accuracy=0.6044

[실험 13/54]  lr=1e-05  scheduler=cosine_with_restarts  dropout=0.1  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.0638  F1=0.1168  Precision=0.6875  Accuracy=0.6182

[실험 14/54]  lr=1e-05  scheduler=cosine_with_restarts  dropout=0.1  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.1663  F1=0.2658  Precision=0.6615  Accuracy=0.6366

[실험 15/54]  lr=1e-05  scheduler=cosine_with_restarts  dropout=0.2  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.2727  F1=0.3933  Precision=0.7050  Accuracy=0.6672

[실험 16/54]  lr=1e-05  scheduler=cosine_with_restarts  dropout=0.2  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.1335  F1=0.2240  Precision=0.6970  Accuracy=0.6343

[실험 17/54]  lr=1e-05  scheduler=cosine_with_restarts  dropout=0.3  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.0000  F1=0.0000  Precision=0.0000  Accuracy=0.6044

[실험 18/54]  lr=1e-05  scheduler=cosine_with_restarts  dropout=0.3  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.0000  F1=0.0000  Precision=0.0000  Accuracy=0.6044

[실험 19/54]  lr=3e-05  scheduler=linear  dropout=0.1  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.3501  F1=0.4514  Precision=0.6351  Accuracy=0.6634

[실험 20/54]  lr=3e-05  scheduler=linear  dropout=0.1  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.3482  F1=0.4580  Precision=0.6691  Accuracy=0.6741

[실험 21/54]  lr=3e-05  scheduler=linear  dropout=0.2  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.6151  F1=0.5977  Precision=0.5814  Accuracy=0.6725

[실험 22/54]  lr=3e-05  scheduler=linear  dropout=0.2  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.2224  F1=0.3329  Precision=0.6609  Accuracy=0.6473

[실험 23/54]  lr=3e-05  scheduler=linear  dropout=0.3  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.0870  F1=0.1541  Precision=0.6716  Accuracy=0.6220

[실험 24/54]  lr=3e-05  scheduler=linear  dropout=0.3  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.0000  F1=0.0000  Precision=0.0000  Accuracy=0.6044

[실험 25/54]  lr=3e-05  scheduler=cosine  dropout=0.1  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.6518  F1=0.6172  Precision=0.5861  Accuracy=0.6802

[실험 26/54]  lr=3e-05  scheduler=cosine  dropout=0.1  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.2727  F1=0.3806  Precision=0.6295  Accuracy=0.6488

[실험 27/54]  lr=3e-05  scheduler=cosine  dropout=0.2  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.4352  F1=0.5062  Precision=0.6048  Accuracy=0.6641

[실험 28/54]  lr=3e-05  scheduler=cosine  dropout=0.2  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.4487  F1=0.5352  Precision=0.6629  Accuracy=0.6917

[실험 29/54]  lr=3e-05  scheduler=cosine  dropout=0.3  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.1992  F1=0.3135  Precision=0.7357  Accuracy=0.6549

[실험 30/54]  lr=3e-05  scheduler=cosine  dropout=0.3  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.0019  F1=0.0039  Precision=1.0000  Accuracy=0.6052

[실험 31/54]  lr=3e-05  scheduler=cosine_with_restarts  dropout=0.1  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.5706  F1=0.5819  Precision=0.5936  Accuracy=0.6756

[실험 32/54]  lr=3e-05  scheduler=cosine_with_restarts  dropout=0.1  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.2398  F1=0.3626  Precision=0.7425  Accuracy=0.6664

[실험 33/54]  lr=3e-05  scheduler=cosine_with_restarts  dropout=0.2  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.8569  F1=0.6106  Precision=0.4743  Accuracy=0.5677

[실험 34/54]  lr=3e-05  scheduler=cosine_with_restarts  dropout=0.2  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.2882  F1=0.4016  Precision=0.6622  Accuracy=0.6603

[실험 35/54]  lr=3e-05  scheduler=cosine_with_restarts  dropout=0.3  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.3075  F1=0.4268  Precision=0.6974  Accuracy=0.6733

[실험 36/54]  lr=3e-05  scheduler=cosine_with_restarts  dropout=0.3  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.0638  F1=0.1164  Precision=0.6600  Accuracy=0.6167

[실험 37/54]  lr=5e-05  scheduler=linear  dropout=0.1  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.2263  F1=0.3259  Precision=0.5821  Accuracy=0.6297

[실험 38/54]  lr=5e-05  scheduler=linear  dropout=0.1  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.5280  F1=0.5566  Precision=0.5884  Accuracy=0.6672

[실험 39/54]  lr=5e-05  scheduler=linear  dropout=0.2  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.4932  F1=0.5508  Precision=0.6235  Accuracy=0.6817

[실험 40/54]  lr=5e-05  scheduler=linear  dropout=0.2  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.4352  F1=0.5149  Precision=0.6303  Accuracy=0.6756

[실험 41/54]  lr=5e-05  scheduler=linear  dropout=0.3  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.0193  F1=0.0372  Precision=0.4762  Accuracy=0.6037

[실험 42/54]  lr=5e-05  scheduler=linear  dropout=0.3  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.2553  F1=0.3692  Precision=0.6667  Accuracy=0.6549

[실험 43/54]  lr=5e-05  scheduler=cosine  dropout=0.1  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.4487  F1=0.5179  Precision=0.6121  Accuracy=0.6695

[실험 44/54]  lr=5e-05  scheduler=cosine  dropout=0.1  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.3578  F1=0.4557  Precision=0.6271  Accuracy=0.6618

[실험 45/54]  lr=5e-05  scheduler=cosine  dropout=0.2  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.0484  F1=0.0885  Precision=0.5208  Accuracy=0.6060

[실험 46/54]  lr=5e-05  scheduler=cosine  dropout=0.2  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.6673  F1=0.5908  Precision=0.5300  Accuracy=0.6343

[실험 47/54]  lr=5e-05  scheduler=cosine  dropout=0.3  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.3366  F1=0.4456  Precision=0.6591  Accuracy=0.6687

[실험 48/54]  lr=5e-05  scheduler=cosine  dropout=0.3  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.1044  F1=0.1824  Precision=0.7200  Accuracy=0.6297

[실험 49/54]  lr=5e-05  scheduler=cosine_with_restarts  dropout=0.1  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.4352  F1=0.5096  Precision=0.6148  Accuracy=0.6687

[실험 50/54]  lr=5e-05  scheduler=cosine_with_restarts  dropout=0.1  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.4159  F1=0.4988  Precision=0.6232  Accuracy=0.6695

[실험 51/54]  lr=5e-05  scheduler=cosine_with_restarts  dropout=0.2  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.5841  F1=0.5853  Precision=0.5864  Accuracy=0.6725

[실험 52/54]  lr=5e-05  scheduler=cosine_with_restarts  dropout=0.2  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.2959  F1=0.4102  Precision=0.6681  Accuracy=0.6634

[실험 53/54]  lr=5e-05  scheduler=cosine_with_restarts  dropout=0.3  batch=16

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.4004  F1=0.5099  Precision=0.7017  Accuracy=0.6955

[실험 54/54]  lr=5e-05  scheduler=cosine_with_restarts  dropout=0.3  batch=32

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

  → Recall=0.0696  F1=0.1265  Precision=0.6923  Accuracy=0.6197

In [71]:
# ── 13. 결과 출력 ──────────────────────────────────────────────
print("\n" + "=" * 60)
print("[4] 전체 실험 결과 요약")
print("=" * 60)

results_df = pd.DataFrame(results).sort_values(
    ["recall", "f1"], ascending=False
).reset_index(drop=True)

# 핵심 컬럼만 출력
summary_cols = ["exp_id", "learning_rate", "scheduler", "dropout",
                "batch_size", "recall", "f1", "precision", "accuracy"]
print(results_df[summary_cols].to_string(index=False))

print("\n" + "=" * 60)
print("[5] Recall 기준 Top 5 조합")
print("=" * 60)
print(results_df[summary_cols].head(5).to_string(index=False))

============================================================
[4] 전체 실험 결과 요약
============================================================
 exp_id  learning_rate            scheduler  dropout  batch_size  recall     f1  precision  accuracy
     33        0.00003 cosine_with_restarts      0.2          16  0.8569 0.6106     0.4743    0.5677
     46        0.00005               cosine      0.2          32  0.6673 0.5908     0.5300    0.6343
     25        0.00003               cosine      0.1          16  0.6518 0.6172     0.5861    0.6802
     21        0.00003               linear      0.2          16  0.6151 0.5977     0.5814    0.6725
     51        0.00005 cosine_with_restarts      0.2          16  0.5841 0.5853     0.5864    0.6725
      9        0.00001               cosine      0.2          16  0.5725 0.5827     0.5932    0.6756
     31        0.00003 cosine_with_restarts      0.1          16  0.5706 0.5819     0.5936    0.6756
     38        0.00005               linear      0.1          32  0.5280 0.5566     0.5884    0.6672
     39        0.00005               linear      0.2          16  0.4932 0.5508     0.6235    0.6817
     28        0.00003               cosine      0.2          32  0.4487 0.5352     0.6629    0.6917
     43        0.00005               cosine      0.1          16  0.4487 0.5179     0.6121    0.6695
     40        0.00005               linear      0.2          32  0.4352 0.5149     0.6303    0.6756
     49        0.00005 cosine_with_restarts      0.1          16  0.4352 0.5096     0.6148    0.6687
     27        0.00003               cosine      0.2          16  0.4352 0.5062     0.6048    0.6641
     50        0.00005 cosine_with_restarts      0.1          32  0.4159 0.4988     0.6232    0.6695
     53        0.00005 cosine_with_restarts      0.3          16  0.4004 0.5099     0.7017    0.6955
     44        0.00005               cosine      0.1          32  0.3578 0.4557     0.6271    0.6618
     19        0.00003               linear      0.1          16  0.3501 0.4514     0.6351    0.6634
     20        0.00003               linear      0.1          32  0.3482 0.4580     0.6691    0.6741
      7        0.00001               cosine      0.1          16  0.3482 0.4500     0.6360    0.6634
     47        0.00005               cosine      0.3          16  0.3366 0.4456     0.6591    0.6687
     35        0.00003 cosine_with_restarts      0.3          16  0.3075 0.4268     0.6974    0.6733
     52        0.00005 cosine_with_restarts      0.2          32  0.2959 0.4102     0.6681    0.6634
     34        0.00003 cosine_with_restarts      0.2          32  0.2882 0.4016     0.6622    0.6603
      3        0.00001               linear      0.2          16  0.2824 0.3935     0.6489    0.6557
     15        0.00001 cosine_with_restarts      0.2          16  0.2727 0.3933     0.7050    0.6672
     26        0.00003               cosine      0.1          32  0.2727 0.3806     0.6295    0.6488
     42        0.00005               linear      0.3          32  0.2553 0.3692     0.6667    0.6549
     32        0.00003 cosine_with_restarts      0.1          32  0.2398 0.3626     0.7425    0.6664
     37        0.00005               linear      0.1          16  0.2263 0.3259     0.5821    0.6297
     22        0.00003               linear      0.2          32  0.2224 0.3329     0.6609    0.6473
     29        0.00003               cosine      0.3          16  0.1992 0.3135     0.7357    0.6549
      2        0.00001               linear      0.1          32  0.1779 0.2784     0.6389    0.6350
     14        0.00001 cosine_with_restarts      0.1          32  0.1663 0.2658     0.6615    0.6366
      8        0.00001               cosine      0.1          32  0.1373 0.2287     0.6827    0.6335
     16        0.00001 cosine_with_restarts      0.2          32  0.1335 0.2240     0.6970    0.6343
      1        0.00001               linear      0.1          16  0.1141 0.1973     0.7284    0.6327
     10        0.00001               cosine      0.2          32  0.1122 0.1933     0.6988    0.6297
      4        0.00001               linear      0.2          32  0.1064 0.1858     0.7333    0.6312
     48        0.00005               cosine      0.3          32  0.1044 0.1824     0.7200    0.6297
     23        0.00003               linear      0.3          16  0.0870 0.1541     0.6716    0.6220
     54        0.00005 cosine_with_restarts      0.3          32  0.0696 0.1265     0.6923    0.6197
     13        0.00001 cosine_with_restarts      0.1          16  0.0638 0.1168     0.6875    0.6182
     36        0.00003 cosine_with_restarts      0.3          32  0.0638 0.1164     0.6600    0.6167
     45        0.00005               cosine      0.2          16  0.0484 0.0885     0.5208    0.6060
     41        0.00005               linear      0.3          16  0.0193 0.0372     0.4762    0.6037
     30        0.00003               cosine      0.3          32  0.0019 0.0039     1.0000    0.6052
      5        0.00001               linear      0.3          16  0.0000 0.0000     0.0000    0.6044
      6        0.00001               linear      0.3          32  0.0000 0.0000     0.0000    0.6044
     11        0.00001               cosine      0.3          16  0.0000 0.0000     0.0000    0.6044
     12        0.00001               cosine      0.3          32  0.0000 0.0000     0.0000    0.6044
     17        0.00001 cosine_with_restarts      0.3          16  0.0000 0.0000     0.0000    0.6044
     18        0.00001 cosine_with_restarts      0.3          32  0.0000 0.0000     0.0000    0.6044
     24        0.00003               linear      0.3          32  0.0000 0.0000     0.0000    0.6044

============================================================
[5] Recall 기준 Top 5 조합
============================================================
 exp_id  learning_rate            scheduler  dropout  batch_size  recall     f1  precision  accuracy
     33        0.00003 cosine_with_restarts      0.2          16  0.8569 0.6106     0.4743    0.5677
     46        0.00005               cosine      0.2          32  0.6673 0.5908     0.5300    0.6343
     25        0.00003               cosine      0.1          16  0.6518 0.6172     0.5861    0.6802
     21        0.00003               linear      0.2          16  0.6151 0.5977     0.5814    0.6725
     51        0.00005 cosine_with_restarts      0.2          16  0.5841 0.5853     0.5864    0.6725

In [72]:
# ── 14. 최적 모델 재학습 (전체 train 데이터 사용) ─────────────
# 기존: full_dataset = AdDataset(df["review_description"], df["is_ad"], tokenizer)
# 변경: train_df 전체로 재학습 (test_df는 건드리지 않음)

print("\n" + "=" * 60)
print("[6] 최적 조합으로 최종 모델 저장")
print("=" * 60)

best = results_df.iloc[0]
print(f"\n  최적 조합")
print(f"    Learning Rate : {best['learning_rate']}")
print(f"    Scheduler     : {best['scheduler']}")
print(f"    Dropout       : {best['dropout']}")
print(f"    Batch Size    : {int(best['batch_size'])}")
print(f"    Recall        : {best['recall']}")
print(f"    F1-score      : {best['f1']}")

set_seed()

full_dataset = AdDataset(
    train_df["review_description"],   # ← 크롤링 데이터 전체
    train_df["is_ad"],
    tokenizer
)

best_model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=2,
    hidden_dropout_prob=float(best["dropout"]),
    attention_probs_dropout_prob=float(best["dropout"]),
    ignore_mismatched_sizes=True,
)

best_args = TrainingArguments(
    output_dir="./electra2crawling_best_model",
    num_train_epochs=EPOCHS,
    per_device_train_batch_size=int(best["batch_size"]),
    learning_rate=float(best["learning_rate"]),
    lr_scheduler_type=best["scheduler"],
    warmup_ratio=0.1,
    weight_decay=0.01,
    logging_steps=50,
    save_strategy="no",
    seed=SEED,
    fp16=torch.cuda.is_available(),
    report_to="none",
)

best_trainer = WeightedTrainer(
    class_weights=class_weights_tensor,
    model=best_model,
    args=best_args,
    train_dataset=full_dataset,
    compute_metrics=compute_metrics,
)
best_trainer.train()

# 최종 Test 평가 출력
final_eval = best_trainer.evaluate(test_dataset)
print("\n  [최종 모델 Test 평가]")
print(f"    Recall    : {final_eval.get('eval_recall',    0):.4f}")
print(f"    F1-score  : {final_eval.get('eval_f1',        0):.4f}")
print(f"    Precision : {final_eval.get('eval_precision', 0):.4f}")
print(f"    Accuracy  : {final_eval.get('eval_accuracy',  0):.4f}")

# 상세 분류 리포트
preds_output = best_trainer.predict(test_dataset)
preds = np.argmax(preds_output.predictions, axis=-1)
print("\n  [Classification Report]")
print(classification_report(
    test_df["is_ad"].values, preds,
    target_names=["비광고(0)", "광고(1)"]
))

# 모델 & 토크나이저 저장
best_model.save_pretrained("electra2crawling_best_model")
tokenizer.save_pretrained("electra2crawling_tokenizer")

print("\n  저장 완료")
print("    electra2crawling_best_model/")
print("    electra2crawling_tokenizer/")
print("    electra2crawling_results_all.csv")
print("\n" + "=" * 60)
print("  파인튜닝 완료!")
print("=" * 60)

============================================================
[6] 최적 조합으로 최종 모델 저장
============================================================

  최적 조합
    Learning Rate : 3e-05
    Scheduler     : cosine_with_restarts
    Dropout       : 0.2
    Batch Size    : 16
    Recall        : 0.8569
    F1-score      : 0.6106

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

ElectraForSequenceClassification LOAD REPORT from: beomi/KcELECTRA-base
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense.bias              | UNEXPECTED |
electra.embeddings.position_ids                   | UNEXPECTED |
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
classifier.dense.bias                             | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

  [최종 모델 Test 평가]
    Recall    : 0.3849
    F1-score  : 0.4778
    Precision : 0.6297
    Accuracy  : 0.6672

  [Classification Report]
              precision    recall  f1-score   support

      비광고(0)       0.68      0.85      0.76       790
       광고(1)       0.63      0.38      0.48       517

    accuracy                           0.67      1307
   macro avg       0.65      0.62      0.62      1307
weighted avg       0.66      0.67      0.65      1307

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  저장 완료
    electra2crawling_best_model/
    electra2crawling_tokenizer/
    electra2crawling_results_all.csv

============================================================
  파인튜닝 완료!
============================================================

In [73]:
# ── 15. 저장된 모델 사용 예시 ──────────────────────────────────
# from transformers import AutoTokenizer, AutoModelForSequenceClassification
# import torch
#
# tokenizer = AutoTokenizer.from_pretrained("electra2naver_tokenizer")
# model = AutoModelForSequenceClassification.from_pretrained("electra2naver_best_model")
# model.eval()
#
# text = "정말 맛있었어요! #광고 #협찬"
# inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=256)
# with torch.no_grad():
#     logits = model(**inputs).logits
# pred = torch.argmax(logits, dim=-1).item()
# print("광고" if pred == 1 else "비광고")